# Generated by Django 5.1 on 2024-09-11 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Devops_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messsage",
            old_name="Message",
            new_name="MessageText",
        ),
    ]
