# Generated by Django 5.1 on 2024-09-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Devops_app", "0002_rename_message_messsage_messagetext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Description", models.TextField()),
                ("Image", models.ImageField(upload_to="")),
            ],
        ),
    ]
