# Generated by Django 5.1 on 2024-09-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Devops_app", "0003_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="Image",
        ),
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
